language: ruby
rvm:
  - 2.4.0

script:
  - scripts/ci_test.sh

# Use container-based infrastructure for faster builds
sudo: false
# Use newer version of Ubuntu for the container, which gets us better
# TLS support. This is important for sites, like pniedzielski.net,
# that only support TLSv1.2.
dist: trusty
