# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenSourceCornell
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Open Source Cornell is an organization for anyone in the Ithaca area
  interested in Free and Open Source software. We have weekly
  meetings, talks, and Linux Installfests every semester.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opensourcecornell.org"
twitter_username: OpenCornell
github_username:  OpenSourceCornell

collections:
  events:
    output: true
    permalink: /event/:year/:month/:day/:title:output_ext

permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - vendor/
